# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Yongfu He's Blog
url: http://yongfuhe2017.github.io
feed: /atom.xml
author_info: <a href="http://yongfuhe2017.github.io/">yongfuhe2017</a>

myblog:
  gavatar: images/2.jpg
  gpname: yongfuhe2017
  linkedin: 
  github: https://github.com/xriver007
  email: xriver007@163.com
  coverimgs: []
  postbgimg: []

categories: [python, books]
