# auto: true

markdown: kramdown
highlighter: rouge
paginate: 8
permalink: /:title
encoding: UTF-8
gems: [jekyll-paginate]

title: Github Blog
url: https://github.com/yongfuhe2017
feed: /atom.xml
author_info: <a href="https://yongfuhe2017.github.io">yongfuhe</a>

myblog:
  gavatar: images/2.jpg
  gpname: 
  linkedin: 
  github: 
  email: mailto:
  coverimgs: []
  postbgimg: []

categories: [python, books]
